bool srs_request # 0 = robot in moto;  1 = attiva SRS;
---
bool srs_response # 0 = richiesta rifiutata; 1 = richiesta accettata;
string reason # motivazione per il rifiiuto della richiesta ("ok" se non ci sono problemi) 