# Goal
float64 vel_setpoint    # setpoint of the robot velocity (m/s)

---
# Result
bool achieved_setpoint  # true if the target velocity is reached
string motivation       # reason if the setpoint was not achieved

---
# Feedback
float64 feedback_vel    # current robot velocity (m/s)